### ISSUE TITLE
Embers light?

### ISSUE THREAD

**Issue by dajare** [rgieseke/base16-textadept#12]
I'm so grateful for this "extension" to Textadept. :)

Is it possible to add the "Embers Light" variant to the collection? It looks like it might have [been available once][1], but hard to tell.

Many thanks!

[1]: https://twitter.com/Andre__LA/status/1242971836763299841

**Comment by rgieseke** [comment]
I'm using Tinted Theming's scheme repo: https://github.com/tinted-theming/schemes

So if it's not there, it will not be auto-generated. You could add a PR to that repo to have it added.

However, I found the old commit which had `embers-light`. I think you could just try putting the color definitions from there into a theme file with all the adjustments for recent Textadept versions.

https://github.com/rgieseke/base16-textadept/blob/3c74baf8fedc381b5eb96c82fb96c71df9db34e8/base16-embers-light.lua#L10-L25

**Comment by dajare** [comment]
Thank you so much for this (and on Christmas Day! :smile:) It took me a moment to work out the adjustments, but it's looking good now. 

I put my [adapted theme file in a gist][1] just in case anyone else looks for this. I'll follow up with `tinted-theming` for future. Thanks again!

[1]: https://gist.github.com/dajare/3150e679cf8f22d9b0ea6210ef42f976

**Comment by dajare** [comment]
I've now added a PR for `embers-light.yaml` at the Tinted Themes schemes repo. Hopefully it will get added!

**Comment by rgieseke** [comment]
Awesome, glad to hear! :christmas_tree:
