### ISSUE TITLE
Enhancement request: add Brushtrees [light|dark]

### ISSUE THREAD

**Issue by dajare** [rgieseke/base16-textadept#5]
I attempted to create a set of ["brushtrees" theme][1] LUA files by doing a "save-as" of the Apathy set already availbe in this repo. I simply copy/pasted in the colour definitions  into the existing files (under new names) ... but that was obviously optimistic!

The result in Textadept was surprising (looked like a "mocha" theme!), and so I obviously did something wrong. 

If you could give me some tips, I would be happy to try again. Otherwise, would it be possible to get the [Brushtrees (default = light) and Brushtrees Dark][1] themes added to the textadept-themes Base 16 set? Thanks!

[1]: https://github.com/WhiteAbeLincoln/base16-brushtrees-scheme

**Comment by rgieseke** [comment]
Hi! Yesterday i was working on updating this collection of themes to the new set of Base16 themes and system that was introduced a while ago ... i hope to finish this up soon and then hopefully this will already be fixed, if not let's revisit!

**Comment by dajare** [comment]
Thanks so much for the reply. It's great to have these themes for Textadept — thanks for making it available! I'll be watching for the update. (I'm subscribed to the Textadept mailing list, so will see any announcment you post there.) 

Best wishes for these strange days.

**Comment by rgieseke** [comment]
Same to you!

At least some time at home for hacking. Find attached the two themes, feedback welcome. There might be some features that look of, i tried to follow the recommendations at http://chriskempson.com/projects/base16/

https://gist.github.com/rgieseke/4fc5024f5447e261ef252e1f5b2cbe31

**Comment by rgieseke** [comment]
I'll keep this open as a reminder ...

**Comment by rgieseke** [comment]
... while i test the themes, i'll update the repo soon.

**Comment by dajare** [comment]
Wow - fast! I just checked them both, and at least in my files they look great. (I'm a enjoy low-contrast themes, but sometimes the contrast is *too* low - "Brushtrees" gets it just about right, for my eye.)

Thanks again for the quick replies, and hope you have good success in thess stay-at-home days.

**Comment by rgieseke** [comment]
Excellent, it's mostly things like indicators or margin markers which aren't immediately visible and i hadn't had a chance to look at.

Perfect timing, i really did the first run generating the templates yesterday :-)

**Comment by rgieseke** [comment]
Fixed a missing 'base' in the function definition: https://gist.github.com/rgieseke/4fc5024f5447e261ef252e1f5b2cbe31/revisions

**Comment by rgieseke** [comment]
Done! Fixed another minor issue ...
