### ISSUE TITLE
linenumber is line_number in the latest TA alpha

### ISSUE THREAD

**Issue by paaguti** [rgieseke/base16-textadept#7]
I'm using base16-materia and I had to
` s/linenumber/lne_number/g`
to make it work with the very latest github TextAdept

**Comment by rgieseke** [comment]
Thanks for the report!

I've updated the template and the themes to the new style used in TA alpha, let me know if there are any issues!

**Comment by rgieseke** [comment]
And hopefully fixed it for real for now ...
