### ISSUE TITLE
Themes not working

### ISSUE THREAD

**Issue by dloiola** [rgieseke/base16-textadept#9]
Hi, 
Need a help, please. I'm following the instructions adding:  `view:set_theme(not CURSES and 'base16-solarized-light' or 'term')` to the *init* file but an error message appear while opening and themes dont load:
**/home/my_name/.textadept/init.lua:3:attempt to call a nil value (method 'set_theme')**

Textadept version 10.8 on Arch Linux

thks

**Comment by rgieseke** [comment]
For TA 10.8 you still need need the old way `buffer:set_theme (and an older version of the code, not the latest commit, it has been already updated to the latest changes in TA 11 alpha),

**Comment by rgieseke** [comment]
I think this one should work with 10.8: https://github.com/rgieseke/base16-textadept/tree/54d635482a3445fb47c2771e7e80a096321e8589

**Comment by dloiola** [comment]
It worked fine, Danke schön :)! And thanks for your work! Why such a great editor like T.a. is so unknown?

**Comment by rgieseke** [comment]
Glad to hear and thanks for the report (i'll add a note to the readme) ... and good question, i don't know :-)

**Comment by dloiola** [comment]
IMHO, it was good to have a place to centralize users and mantainers and make them interact (e.g. Void's subreddit, Funtoo's Telegram Group). I'm not a programmer, but I use a lot text editors for Markdown, LaTeX (ConTeXt), general notes, and now and then some HTML/CSS and Python lines. I used VS Code and Kate fot that, but T.a. is very lighter and faster and its keyboard driven method is fantastic.

**Comment by rgieseke** [comment]
Ye, i think most of Textadept's community happens on its Mailing list, and now here and there on GitHub for related sub-modules. Mitchell (Textadept's author) is keen on doing lots of things himself so the Textadept Wiki is also self-hosted.
I run the Textadept Twitter account and maintain the source code mirror here on GitHub, i think it's hard to get any group to use one medium, though the mailing list is working well and quite responsive!

**Comment by dloiola** [comment]
I understand. I dont have too much time but I would like to contribute with some visuals (ie screenshots to the readme.md) and maybe translating to pt_BR. How many active contributor TA has?

**Comment by rgieseke** [comment]
Hard to say what's 'active' ... here is a list of some of the people who contributed: https://foicica.com/textadept/THANKS.html

Here you can see activity on GitHub, e.g. personal `.textadept` directories: https://github.com/search?o=desc&q=textadept&s=updated&type=Repositories

There is no pt_BR translation yet I think, so that would surely be very welcome, best to send it to Mitchell or the mailing list!

**Comment by dloiola** [comment]
Good, I'll subscribe to code+subscribe. Questions like "how to do this?" may be addressed to this mailing list too?

**Comment by rgieseke** [comment]
Yes! You can click around the archive at https://foicica.com/lists/code/ to get a feel for the list, e.g. this month https://foicica.com/lists/code/202007/index.html

**Comment by dloiola** [comment]
Ok, muito obrigado e de novo, parabéns pelo trabalho 👏👏👏👏! 
Ok, thanks e congratulations for the work👏👏👏👏!
